name: Culinária
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ceb688'
    - '#b5170e'
    - '#fefefe'
    - '#a18556'
    - '#f0ddb2'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
