name: Culinária
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#06050a'
    - '#cab78d'
    - '#9e7e57'
    - '#ae5511'
  brandStrength: 0
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
